In [5]:
from src import full_pcd_dataset
import importlib
importlib.reload(full_pcd_dataset)

data_creator = full_pcd_dataset.FullPCDDataCreator()

In [6]:
from pathlib import Path
import open3d as o3d

model_dir = Path("./data/models")
model_list = list(model_dir.glob("*"))
model_list

[WindowsPath('data/models/combwrench.obj'),
 WindowsPath('data/models/drill.obj'),
 WindowsPath('data/models/hammer.obj'),
 WindowsPath('data/models/screwdriver.obj'),
 WindowsPath('data/models/wrench.obj')]

In [7]:
# for model_path in model_list:
#     model = o3d.io.read_triangle_mesh(model_path)
#     model.translate(-model.get_center())
#     model.scale(1000, center=[0,0,0])
#     o3d.io.write_triangle_mesh(model_path, model)
    # aabb = model.get_axis_aligned_bounding_box()
    # results = aabb.get_extent()




In [8]:
results = []
for model_path in model_list:
    model = o3d.io.read_triangle_mesh(model_path)
    aabb = model.get_axis_aligned_bounding_box()
    results.append(model.get_center())
    results.append(aabb.get_extent())

results

[array([-2.13195193e-08,  2.39145649e-09,  2.05782756e-10]),
 array([0.13381051, 0.0404716 , 0.0182499 ]),
 array([6.95198576e-09, 5.77284670e-09, 3.86663662e-09]),
 array([0.258097 , 0.2175772, 0.0813883]),
 array([-1.21696391e-07, -1.48775462e-08,  3.92335271e-09]),
 array([0.334803 , 0.1340526, 0.0388809]),
 array([-1.92370077e-09, -1.50103201e-10, -1.28747875e-09]),
 array([0.2194488, 0.0345184, 0.0363305]),
 array([-1.60746981e-09, -3.15019086e-09, -2.13113283e-09]),
 array([0.2132688, 0.0680763, 0.0237962])]

In [9]:
data_creator.generate_data_6d(model_list,["combwrench",  "drill", "hammer", "screwdriver","wrench"], 300000)

Subfunction took 0.1217 seconds
sample 1000 took 32.5053 seconds
sample 2000 took 29.5512 seconds
sample 3000 took 30.7248 seconds
sample 4000 took 28.7477 seconds
sample 5000 took 27.7644 seconds
sample 6000 took 27.8299 seconds
sample 7000 took 27.9470 seconds
sample 8000 took 27.8394 seconds
sample 9000 took 28.3057 seconds
sample 10000 took 27.6728 seconds
sample 11000 took 29.7648 seconds
sample 12000 took 27.2029 seconds
sample 13000 took 27.4061 seconds
sample 14000 took 27.9602 seconds
sample 15000 took 27.8805 seconds
sample 16000 took 27.3135 seconds
sample 17000 took 27.7521 seconds
sample 18000 took 27.5452 seconds
sample 19000 took 27.3707 seconds
sample 20000 took 27.5809 seconds
sample 21000 took 29.0345 seconds
sample 22000 took 28.4186 seconds
sample 23000 took 28.4081 seconds
sample 24000 took 29.2173 seconds
sample 25000 took 29.2405 seconds
sample 26000 took 29.3973 seconds
sample 27000 took 32.9673 seconds
sample 28000 took 28.9337 seconds
sample 29000 took 30.4383

In [ ]:
0.4*100000/3600

In [ ]:
data_creator.generate_data_6d.


In [ ]:

np.savez(f"full_pcd_10000_samples.npz", pcds=data_creator.pcd_array,
                 transformations=data_creator.transformation_array, rotations_6d=data_creator.d6_rotations_array, positions=data_creator.position_array, classes=data_creator.class_array)

In [ ]:
import numpy as np
varray = np.asarray(model.vertices)
z = varray[:,0]
print(max(z), min(z), max(z) - min(z))


In [1]:
import numpy as np
import open3d as o3d
data = np.load("data/full_pcd_300000_samples_6d.npz")

pcd = o3d.geometry.PointCloud(o3d.utility.Vector3dVector(data['pcds'][0]))
data

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


NpzFile 'data/full_pcd_300000_samples_6d.npz' with keys: pcds, transformations, rotations_6d, positions, classes

In [ ]:
np.savez(f"full_pcd_150000_samples_6d_1.npz", pcds=data["pcds"][0:150000],
                 transformations=data["transformations"][0:150000], rotations_6d=data["rotations_6d"][0:150000], positions=data["positions"][0:150000], classes=data["classes"][0:150000])


In [4]:
np.savez(f"full_pcd_150000_samples_6d_2.npz", pcds=data["pcds"][150000:300000],
                 transformations=data["transformations"][150000:300000], rotations_6d=data["rotations_6d"][150000:300000], positions=data["positions"][150000:300000], classes=data["classes"][150000:300000])

In [ ]:
data['transformations'][0]

In [ ]:
np.sum(np.abs(data['positions'][0]))/3

In [ ]:
np.asarray(pcd.points)

In [2]:
pcds = []
for i in range(100, 250):
    pcd = o3d.geometry.PointCloud(o3d.utility.Vector3dVector(data['pcds'][i]))
    pcd.paint_uniform_color([0.5, 0.5, 0.5])
    pcds.append(pcd)
o3d.visualization.draw_geometries(pcds)

In [ ]:
from torch.utils.data import DataLoader
dataset = full_pcd_dataset.FullPCDDataset("full_pcd_300000_samples.npz")
train_loader = DataLoader(dataset, batch_size=10, shuffle=True)

In [ ]:
from tqdm import tqdm
progress_bar = tqdm(train_loader, desc="Training")
for batch in progress_bar:
    print(batch[1])
    pass

In [ ]:
np.tan(np.pi/4)*3-0.25