In [1]:
from src import full_pcd_dataset
import importlib
importlib.reload(full_pcd_dataset)

data_creator = full_pcd_dataset.FullPCDDataCreator()

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [4]:
from pathlib import Path
import open3d as o3d

model_dir = Path("./data/hammers")
model_list = list(model_dir.glob("*"))
model_list

[WindowsPath('data/hammers/hammer_0.obj'),
 WindowsPath('data/hammers/hammer_1.obj'),
 WindowsPath('data/hammers/hammer_2.obj'),
 WindowsPath('data/hammers/hammer_3.obj'),
 WindowsPath('data/hammers/hammer_4.obj')]

In [ ]:
# for model_path in model_list:
#     model = o3d.io.read_triangle_mesh(model_path)
#     model.translate(-model.get_center())
#     model.scale(0.001, center=[0,0,0])
#     o3d.io.write_triangle_mesh(model_path, model)
#     aabb = model.get_axis_aligned_bounding_box()
#     results = aabb.get_extent()




In [7]:
results = []
for model_path in model_list:
    model = o3d.io.read_triangle_mesh(model_path)
    aabb = model.get_axis_aligned_bounding_box()
    results.append(model.get_center())
    results.append(aabb.get_extent())

results

[array([ 1.06972144e-07, -2.50934152e-09,  2.56585176e-08]),
 array([0.42088601, 0.1561596 , 0.0427159 ]),
 array([-1.70406585e-08,  7.27977451e-09, -7.95439494e-09]),
 array([0.331536 , 0.1532779, 0.0390123]),
 array([-6.86945494e-08,  5.84703239e-09, -4.94012118e-09]),
 array([0.33303139, 0.13632961, 0.038375  ]),
 array([ 8.58447656e-08,  2.44651001e-08, -1.24818662e-08]),
 array([0.33428951, 0.14471459, 0.0360433 ]),
 array([-2.00447782e-07, -2.25467247e-08,  8.63935400e-09]),
 array([0.334803 , 0.1340526, 0.0388809])]

In [8]:
data_creator.generate_data_6d(model_list,["combwrench",  "drill", "hammer", "screwdriver","wrench"], 200000)

Subfunction took 0.0738 seconds
sample 1000 took 22.2750 seconds
sample 2000 took 18.5019 seconds
sample 3000 took 18.9975 seconds
sample 4000 took 19.3319 seconds
sample 5000 took 19.1657 seconds
sample 6000 took 19.0756 seconds
sample 7000 took 18.7285 seconds
sample 8000 took 19.1109 seconds
sample 9000 took 18.9849 seconds
sample 10000 took 19.3487 seconds
sample 11000 took 19.1095 seconds
sample 12000 took 18.8607 seconds
sample 13000 took 18.8503 seconds
sample 14000 took 18.6598 seconds
sample 15000 took 18.9180 seconds
sample 16000 took 18.8099 seconds
sample 17000 took 19.1623 seconds
sample 18000 took 18.9565 seconds
sample 19000 took 18.6677 seconds
sample 20000 took 18.7493 seconds
sample 21000 took 18.5640 seconds
sample 22000 took 18.7149 seconds
sample 23000 took 18.3249 seconds
sample 24000 took 18.9252 seconds
sample 25000 took 18.5925 seconds
sample 26000 took 18.5311 seconds
sample 27000 took 18.4569 seconds
sample 28000 took 18.3468 seconds
sample 29000 took 19.0532

In [ ]:
0.4*100000/3600

In [ ]:
data_creator.generate_data_6d.


In [ ]:

np.savez(f"full_pcd_10000_samples.npz", pcds=data_creator.pcd_array,
                 transformations=data_creator.transformation_array, rotations_6d=data_creator.d6_rotations_array, positions=data_creator.position_array, classes=data_creator.class_array)

In [ ]:
import numpy as np
varray = np.asarray(model.vertices)
z = varray[:,0]
print(max(z), min(z), max(z) - min(z))


In [9]:
import numpy as np
import open3d as o3d
data = np.load("data/full_pcd_200000_samples_6d.npz")

pcd = o3d.geometry.PointCloud(o3d.utility.Vector3dVector(data['pcds'][0]))
data

NpzFile 'data/full_pcd_200000_samples_6d.npz' with keys: pcds, transformations, rotations_6d, positions, classes

In [2]:
import numpy as np
first_part = np.load("data/full_pcd_150000_samples_6d_1.npz")
second_part = np.load("data/full_pcd_150000_samples_6d_2.npz")
# first_part

In [7]:
np.savez("full_pcd_300000_samples_6d.npz", pcds = np.concatenate([first_part["pcds"], second_part["pcds"]]),
                                                                 transformations=np.concatenate([first_part["transformations"], second_part["transformations"]]),
                                                                 rotations_6d=np.concatenate([first_part["rotations_6d"], second_part["rotations_6d"]]),
                                                                 positions=np.concatenate([first_part["positions"], second_part["positions"]]),
                                                                 classes=np.concatenate([first_part["classes"], second_part["classes"]]))

: 

In [4]:
np.concatenate([first_part["pcds"], second_part["pcds"]])

: 

In [3]:
first_part["pcds"]

array([[[-0.76254422,  0.24892272,  1.91962412],
        [-0.75160021,  0.28859731,  1.8939306 ],
        [-0.77103352,  0.24168802,  1.92492181],
        ...,
        [-0.72934326,  0.29043516,  1.88850485],
        [-0.72735384,  0.29486564,  1.89245603],
        [-0.73153927,  0.30989938,  1.88316734]],

       [[-0.22718109,  0.79814367,  1.43344281],
        [-0.22358073,  0.82527614,  1.37879752],
        [-0.28587657,  0.75731497,  1.49923447],
        ...,
        [-0.15849028,  0.8721381 ,  1.29453983],
        [-0.28402365,  0.76551433,  1.46452059],
        [-0.18111693,  0.82307426,  1.36450727]],

       [[-0.1344371 ,  0.37865952,  1.37428584],
        [-0.09385236,  0.46349691,  1.37648648],
        [-0.36128537,  0.33369877,  1.37618804],
        ...,
        [-0.3041891 ,  0.3183742 ,  1.36523888],
        [-0.27189862,  0.35838907,  1.38797749],
        [-0.2887007 ,  0.3261488 ,  1.3614348 ]],

       ...,

       [[-0.08276277,  0.27356357,  0.770329  ],
        [-0

In [ ]:
np.savez(f"full_pcd_150000_samples_6d_1.npz", pcds=data["pcds"][0:150000],
                 transformations=data["transformations"][0:150000], rotations_6d=data["rotations_6d"][0:150000], positions=data["positions"][0:150000], classes=data["classes"][0:150000])


In [4]:
np.savez(f"full_pcd_150000_samples_6d_2.npz", pcds=data["pcds"][150000:300000],
                 transformations=data["transformations"][150000:300000], rotations_6d=data["rotations_6d"][150000:300000], positions=data["positions"][150000:300000], classes=data["classes"][150000:300000])

In [ ]:
data['transformations'][0]

In [ ]:
np.sum(np.abs(data['positions'][0]))/3

In [ ]:
np.asarray(pcd.points)

In [10]:
pcds = []
for i in range(100, 250):
    pcd = o3d.geometry.PointCloud(o3d.utility.Vector3dVector(data['pcds'][i]))
    pcd.paint_uniform_color([0.5, 0.5, 0.5])
    pcds.append(pcd)
o3d.visualization.draw_geometries(pcds)

In [ ]:
from torch.utils.data import DataLoader
dataset = full_pcd_dataset.FullPCDDataset("full_pcd_300000_samples.npz")
train_loader = DataLoader(dataset, batch_size=10, shuffle=True)

In [ ]:
from tqdm import tqdm
progress_bar = tqdm(train_loader, desc="Training")
for batch in progress_bar:
    print(batch[1])
    pass

In [ ]:
np.tan(np.pi/4)*3-0.25