In [1]:
from src import full_pcd_dataset
import importlib
importlib.reload(full_pcd_dataset)

data_creator = full_pcd_dataset.FullPCDDataCreator()

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
from pathlib import Path
import open3d as o3d

model_dir = Path("./data/models")
model_list = list(model_dir.glob("*"))
model_list

[WindowsPath('data/models/combwrench.obj'),
 WindowsPath('data/models/drill.obj'),
 WindowsPath('data/models/hammer.obj'),
 WindowsPath('data/models/screwdriver.obj'),
 WindowsPath('data/models/wrench.obj')]

In [3]:
# for model_path in model_list:
#     model = o3d.io.read_triangle_mesh(model_path)
#     model.translate(-model.get_center())
#     model.scale(1000, center=[0,0,0])
#     o3d.io.write_triangle_mesh(model_path, model)
    # aabb = model.get_axis_aligned_bounding_box()
    # results = aabb.get_extent()




In [4]:
results = []
for model_path in model_list:
    model = o3d.io.read_triangle_mesh(model_path)
    aabb = model.get_axis_aligned_bounding_box()
    results.append(aabb.get_extent())

results

[array([0.13381051, 0.0404716 , 0.0182499 ]),
 array([0.258097 , 0.2175772, 0.0813883]),
 array([0.334803 , 0.1340526, 0.0388809]),
 array([0.2194488, 0.0345184, 0.0363305]),
 array([0.2132688, 0.0680763, 0.0237962])]

In [5]:
data_creator.generate_data(model_list,["combwrench",  "drill", "hammer", "screwdriver","wrench"], 30000)

Generating sample 0/30000
Generating sample 1000/30000
Generating sample 2000/30000
Generating sample 3000/30000
Generating sample 4000/30000
Generating sample 5000/30000
Generating sample 6000/30000
Generating sample 7000/30000
Generating sample 8000/30000
Generating sample 9000/30000
Generating sample 10000/30000
Generating sample 11000/30000
Generating sample 12000/30000
Generating sample 13000/30000
Generating sample 14000/30000
Generating sample 15000/30000
Generating sample 16000/30000
Generating sample 17000/30000
Generating sample 18000/30000
Generating sample 19000/30000
Generating sample 20000/30000
Generating sample 21000/30000
Generating sample 22000/30000
Generating sample 23000/30000
Generating sample 24000/30000
Generating sample 25000/30000
Generating sample 26000/30000
Generating sample 27000/30000
Generating sample 28000/30000
Generating sample 29000/30000


In [7]:
import numpy as np
varray = np.asarray(model.vertices)
z = varray[:,0]
print(max(z), min(z), max(z) - min(z))


0.07684080302715302 -0.13642799854278564 0.21326880156993866


In [8]:
data = np.load("full_pcd_10000_samples.npz")

pcd = o3d.geometry.PointCloud(o3d.utility.Vector3dVector(data['pcds'][0]))
data

NpzFile 'full_pcd_10000_samples.npz' with keys: pcds, transformations, quaternions, positions, classes

In [10]:
pcds = []
for i in range(1000):
    pcd = o3d.geometry.PointCloud(o3d.utility.Vector3dVector(data['pcds'][i]))
    pcds.append(pcd)
o3d.visualization.draw_geometries(pcds)

In [3]:
from torch.utils.data import DataLoader
dataset = full_pcd_dataset.FullPCDDataset("full_pcd_1000_samples.npz")
train_loader = DataLoader(dataset, batch_size=10, shuffle=True)

In [6]:
from tqdm import tqdm
progress_bar = tqdm(train_loader, desc="Training")
for batch in progress_bar:
    print(batch[1])
    pass

Training: 100%|██████████| 100/100 [00:00<00:00, 881.20it/s]

[tensor([3, 4, 4, 1, 4, 0, 1, 0, 0, 2]), tensor([[[ 0.4305, -0.6145, -0.6611,  0.1594],
         [ 0.8625,  0.0641,  0.5021,  1.2656],
         [-0.2661, -0.7863,  0.5576,  1.7702],
         [ 0.0000,  0.0000,  0.0000,  1.0000]],

        [[-0.4247,  0.4289,  0.7973, -0.0880],
         [-0.8930, -0.3432, -0.2910,  0.5474],
         [ 0.1488, -0.8356,  0.5288,  1.7002],
         [ 0.0000,  0.0000,  0.0000,  1.0000]],

        [[-0.6246,  0.7798, -0.0425, -0.6638],
         [-0.1500, -0.0664,  0.9864, -2.4049],
         [ 0.7664,  0.6225,  0.1585,  2.2966],
         [ 0.0000,  0.0000,  0.0000,  1.0000]],

        [[ 0.0392,  0.8776, -0.4778, -0.5760],
         [ 0.3733, -0.4564, -0.8077, -0.7931],
         [-0.9269, -0.1467, -0.3455,  1.1509],
         [ 0.0000,  0.0000,  0.0000,  1.0000]],

        [[-0.8059,  0.5453, -0.2304,  1.6238],
         [-0.4484, -0.8164, -0.3640,  0.1480],
         [-0.3866, -0.1900,  0.9024,  1.7652],
         [ 0.0000,  0.0000,  0.0000,  1.0000]],

        [

In [18]:
np.tan(np.pi/4)*3-0.25

2.7499999999999996